#pragma once
#include <GLFW\glfw3.h>

// clang-format off
#define NY_MOUSE_BUTTON_1       GLFW_MOUSE_BUTTON_1
#define NY_MOUSE_BUTTON_2       GLFW_MOUSE_BUTTON_2
#define NY_MOUSE_BUTTON_3       GLFW_MOUSE_BUTTON_3
#define NY_MOUSE_BUTTON_4       GLFW_MOUSE_BUTTON_4
#define NY_MOUSE_BUTTON_5       GLFW_MOUSE_BUTTON_5
#define NY_MOUSE_BUTTON_6       GLFW_MOUSE_BUTTON_6
#define NY_MOUSE_BUTTON_7       GLFW_MOUSE_BUTTON_7
#define NY_MOUSE_BUTTON_8       GLFW_MOUSE_BUTTON_8
#define NY_MOUSE_BUTTON_LAST    GLFW_MOUSE_BUTTON_LAST
#define NY_MOUSE_BUTTON_LEFT    GLFW_MOUSE_BUTTON_LEFT
#define NY_MOUSE_BUTTON_RIGHT   GLFW_MOUSE_BUTTON_RIGHT
#define NY_MOUSE_BUTTON_MIDDLE  GLFW_MOUSE_BUTTON_MIDDLE
// clang-format on